apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiotmp
  labels:
    app: wiotmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wiotemphu
  template:
    metadata:
      labels:
        app: wiotemphu
    spec:
      containers:
        - name: wiotemphu
          image: dukeman/wiotemp
          command: ["/bin/app"]
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: wiotemphu
